RATINGS_DATA= "movielens/100k-ratings"
MOVIES_DATA= "movielens/100k-movies"

SPLIT = "train"

RETRIEVAL_MODEL_PATH = "MODEL/RETREVAL_MODEL/"
RANKING_MODEL_PATH = "MODEL/RANKING_MODEL/"

TEMP = False
EPOCHS = 2